movie-recommendation-api:
  api:
    key: "${HIDDEN_API_KEY}"

spring:
  datasource:
    url: jdbc:mysql://localhost:9199/movie_recommendation?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      # MySQL Dialect 설정
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
