movie-recommendation-api:
  api:
    key: "663790bc503369ee6df38ca4045f5837"

spring:
  datasource:
    url: jdbc:mysql://localhost:9199/movie_recommendation?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      # MySQL Dialect 설정
      dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
  jwt:
    secret: qksjdofkejqndkfmoqkmdmieu@!jfkas!@fdfa
